### ISSUE TITLE
Tried to run without success

### ISSUE THREAD

**Issue by robsonfelix** [nesterovsky-bros/KB#1]
Hi,

I tried to play the game without success. I have reproduced successfully every step of the installation. In the end, the getEntities returns NULL at the Value column, and the second resultset returns NULL as well...

Maybe the Person database is not that good. Not sure what to look for.

Is there anything you suggest I can try to successfully play the game?

**Comment by vnesterovsky** [comment]
1. Do you mean it does not work at all or do you get empty result set when you narrowed results set to the minimum?

What do you get when you call GetEntities on earlier steps?

Can we see an execution plans?

2. The sample in this GitHub uses very limited set of questions (predicates). More "good" questions you have the better result you get.

**Comment by robsonfelix** [comment]
GetNextPredicates works up to a point in which it returns NULL. By then I call GetEntities with the same request and I get some rows with an EntityID but no values.

Example:

```SQL 
declare @params xml = '
 <request>
   <question name="IsTall" answer="0.5"/>
   <question name="IsPolitician" answer="1"/>
   <question name="IsReligious" answer="1"/>
   <question name="IsPresident" answer="1"/>
   <question name="IsMilitary" answer="0"/>
   <question name="WasBornInRussiaOrInSovietUnion" answer="0"/>
   <question name="WasBornInUSA" answer="1"/>
 </request>';
declare @result xml;


execute Data.GetNextPredicates  @params = @params,  @result = @result output;

select @result;

```

This returns NULL. Now I call GetEntities with the same request. It returns 3 entities (250490, 663204, 1172020) and no Value (NULL). The second recordset of the output is also NULL.

**Comment by robsonfelix** [comment]
I tried passing a property as a parameter and now I am getting values... In this test I used:
```SQL
declare @params xml = '
 <request>
   <question name="IsTall" answer="0.5"/>
   <question name="IsPolitician" answer="1"/>
   <question name="IsReligious" answer="1"/>
   <question name="IsPresident" answer="1"/>
   <question name="IsMilitary" answer="0"/>
   <question name="WasBornInRussiaOrInSovietUnion" answer="0"/>
   <question name="WasBornInUSA" answer="1"/>
 </request>';
declare @result xml;


execute Data.GetNextPredicates  @params = @params,  @result = @result output;

execute Data.GetEntities  @params = @params, @property = 'rdf-schema#label';


select @result;
```

and I got the property values for those entities. I believe that means the search is working fine.

On the other hand, I tried to "search" for a particular case (Tom Cruise for example), and trying to answer question as to 'point to him' did not work. What does it mean?

**Comment by vnesterovsky** [comment]
> On the other hand, I tried to "search" for a particular case (Tom Cruise for example), and 
> trying to answer question as to 'point to him' did not work. What does it mean?

This could mean that we did not accurately define the predicate, or that what you think is true about Tom Cruise is not what People table stores, or you're run into imprecise predicate: e.g. "Tall" percepted differently by different people.

**Comment by vnesterovsky** [comment]
> Now I call GetEntities with the same request. 
> It returns 3 entities (250490, 663204, 1172020) and no Value (NULL). The second recordset of the output is also NULL.

Can you inspect what you get on:

```
select 
  P.EntityID, T.Name, P.Value
from 
  Data.Property P
  inner join
  Data.PropertyType T
  on
    P.PropertyID = T.PropertyID
where
  P.EntityID in (250490, 663204, 1172020)
```

**Comment by robsonfelix** [comment]
https://pastebin.com/xeZ9kZLe

**Comment by anesterovsky** [comment]
250490 | rdf-schema#label | Bill Clinton
663204 | rdf-schema#label | Marriner Stoddard Eccles
1172020 | rdf-schema#label | Presidency of Ronald Reagan
(I guess it means Ronald Reagan, since spouse_label=Nancy Reagan).

Unfortunatelly, not Tom Cruise...

**Comment by vnesterovsky** [comment]
I see it brings some set, and it seems "rdf-schema#label" is defined.
Not sure why do you have null value.

Can you please run your GetEntities with @debug = 1?
This will print SQL that it executes.

**Comment by robsonfelix** [comment]
I tried with different approaches. It does work.

However in most cases it returns A LOT of entities, and stop asking questions... See this example:

 <request>
 <question name="IsTall" answer="0"/>
 <question name="HasAwards" answer="0"/>
 <question name="IsPolitician" answer="0"/>
 <question name="IsArtist" answer="1"/>
 <question name="IsActor" answer="1"/>
 <question name="WasBornInUnitedKingdomOrIreland" answer="1"/>
 <question name="WarBornInUSA" answer="0"/>
 <question name="IsReligious" answer="0"/>
 </request>

This example returned 552 rows...

**Comment by vnesterovsky** [comment]
> However in most cases it returns A LOT of entities, and stop asking questions...

I think it runs out of questions.
Our goal was to prove the approach is viable, and we think it is.
But to get a good quality you should define more questions.
The better question isolates some group of entities the better its contribution can be.
See "Predicate definitions" for details.

**Comment by robsonfelix** [comment]
Thanks dude... Will look into it.
